/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataPanel: typeof import('./theme/components/DataPanel.vue')['default']
    'Fa6Solid:heartPulse': typeof import('~icons/fa6-solid/heart-pulse')['default']
    Layout: typeof import('./theme/components/Layout.vue')['default']
    NavLink: typeof import('./theme/components/NavLink.vue')['default']
    NavLinks: typeof import('./theme/components/NavLinks.vue')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
  }
}
